repos:
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.2.1
    hooks:
      - id: fmt
      - id: cargo-check

  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.19.4
    hooks:
      - id: cargo-deny
        args: ["check","licenses"]
