# UNDERTONE SERVER CONFIGURATION
# This file is loaded when the CLI server is executed.
# It can be overwritten with a local and or dev file.

# The name of the server which will be displayed on the website and in users history/favorites
server_name = "A Default Undertone Server"

# A description of the server displayed in finders and website.
server_desc = "A Default Undertone Community"

# Port for your server, we recommed leaving this as default unless you know what you are doing
server_port = 9991

# Relative path to your servers icon (displayed to clients and on the web)
server_icon = "undertone.png"

# Set to `true` to prevent anyone without admin privileges from connecting.
# Useful for maintenance or development.
admin_only = true

# Database Settings
[db]
# Address to connect to the db
addr="localhost"
# Port (ref your database docs or server host for the port)
port=5433
# Change to a unique user name that cannot be guessed.
user="default_user"
# Change to strong password that cannot be easily guessed.
pass="default_pass"
# Do not use the default database name, use something unique.
name="default_database"
# Options: pgsql (mysql, mongodb and other db solutions planned)
kind="mysql"
