[package]
name = "undertone-cli-server"
version = "0.1.0"
authors = ["Victoria Beauray Sagady <cephypi@pm.me>"]
license = "AGPL-3.0"
description = "Undertone voice chat server run from the command line."
publish = false
edition = "2024"

[dependencies]
undertone-serialization.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
tokio-postgres = "0.7.17"
ractor = "0.15.12"
