[package]
name = "undertone-cli-server"
description = "Undertone server run from the command line."
keywords.workspace = true
version.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
publish.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation="https://dev.undertone.chat/undertone-cli-server"

[dependencies]
undertone-serialization.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
tokio-postgres = "0.7.17"
ractor = "0.15.12"
serde = { version = "1.0", features = ["derive"]}
config = "0.15"
thiserror.workspace = true

[dev-dependencies]
# Only used for testing.
serde_json = "1.0"
toml = "1.1"
serde-saphyr = "0.0.25"
ron = "0.12"
