[package]
name = "undertone-client"
description = "Undertone dioxus client to connect to undertone servers."
keywords.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
readme.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.undertone.chat/undertone-client"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = {version="0.7.6", features = ["logger"]}
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
tracing.workspace = true
tracing-subscriber.workspace = true
addr = "0.15.6"
crossbeam-channel = "0.5.15"
tokio.workspace = true
undertone-serialization.workspace = true

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
