[package]
name = "client"
version = "0.1.0"
authors = ["Victoria Beauray Sagady <cephypi@pm.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-native = { git = "https://github.com/DioxusLabs/blitz", rev = "d4650c4", features = ["prelude"] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
tracing.workspace = true
tracing-subscriber.workspace = true

# [features]
# default = ["desktop"]
# web = ["dioxus-native/web"]
# desktop = ["dioxus-native/desktop"]
# mobile = ["dioxus-native/mobile"]
