[package]
name = "undertone-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = {version="0.7.6", features = ["logger"]}
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
tracing.workspace = true
tracing-subscriber.workspace = true
addr = "0.15.6"
crossbeam-channel = "0.5.15"
tokio.workspace = true
undertone-serialization.workspace = true

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
